import type { Metadata } from "next";
import "@/app/globals.css";
import OrganizationHeader from "@/components/OrganizationHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <OrganizationHeader />
      {children}
    </div>
  );
}
