import type { Metadata } from "next";
import { poppins } from "@/lib/font";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={`${poppins.className} antialiased `}>{children}</div>;
}
